package com.android.billingclient.api;

import com.android.billingclient.api.c;

/* JADX INFO: loaded from: classes.dex */
public abstract class h {
    public static final c A;
    public static final c B;
    public static final c C;
    public static final c D;
    public static final c E;
    public static final c F;
    public static final c a;
    public static final c b;
    public static final c c;
    public static final c d;
    public static final c e;
    public static final c f;
    public static final c g;
    public static final c h;
    public static final c i;
    public static final c j;
    public static final c k;
    public static final c l;
    public static final c m;
    public static final c n;
    public static final c o;
    public static final c p;
    public static final c q;
    public static final c r;
    public static final c s;
    public static final c t;
    public static final c u;
    public static final c v;
    public static final c w;
    public static final c x;
    public static final c y;
    public static final c z;

    static {
        c.a aVarNewBuilder = c.newBuilder();
        aVarNewBuilder.setResponseCode(3);
        aVarNewBuilder.setDebugMessage("Google Play In-app Billing API version is less than 3");
        a = aVarNewBuilder.build();
        c.a aVarNewBuilder2 = c.newBuilder();
        aVarNewBuilder2.setResponseCode(3);
        aVarNewBuilder2.setDebugMessage("Google Play In-app Billing API version is less than 9");
        b = aVarNewBuilder2.build();
        c.a aVarNewBuilder3 = c.newBuilder();
        aVarNewBuilder3.setResponseCode(3);
        aVarNewBuilder3.setDebugMessage("Billing service unavailable on device.");
        c = aVarNewBuilder3.build();
        c.a aVarNewBuilder4 = c.newBuilder();
        aVarNewBuilder4.setResponseCode(5);
        aVarNewBuilder4.setDebugMessage("Client is already in the process of connecting to billing service.");
        d = aVarNewBuilder4.build();
        c.a aVarNewBuilder5 = c.newBuilder();
        aVarNewBuilder5.setResponseCode(5);
        aVarNewBuilder5.setDebugMessage("The list of SKUs can't be empty.");
        e = aVarNewBuilder5.build();
        c.a aVarNewBuilder6 = c.newBuilder();
        aVarNewBuilder6.setResponseCode(5);
        aVarNewBuilder6.setDebugMessage("SKU type can't be empty.");
        f = aVarNewBuilder6.build();
        c.a aVarNewBuilder7 = c.newBuilder();
        aVarNewBuilder7.setResponseCode(5);
        aVarNewBuilder7.setDebugMessage("Product type can't be empty.");
        g = aVarNewBuilder7.build();
        c.a aVarNewBuilder8 = c.newBuilder();
        aVarNewBuilder8.setResponseCode(-2);
        aVarNewBuilder8.setDebugMessage("Client does not support extra params.");
        h = aVarNewBuilder8.build();
        c.a aVarNewBuilder9 = c.newBuilder();
        aVarNewBuilder9.setResponseCode(5);
        aVarNewBuilder9.setDebugMessage("Invalid purchase token.");
        i = aVarNewBuilder9.build();
        c.a aVarNewBuilder10 = c.newBuilder();
        aVarNewBuilder10.setResponseCode(6);
        aVarNewBuilder10.setDebugMessage("An internal error occurred.");
        j = aVarNewBuilder10.build();
        c.a aVarNewBuilder11 = c.newBuilder();
        aVarNewBuilder11.setResponseCode(5);
        aVarNewBuilder11.setDebugMessage("SKU can't be null.");
        k = aVarNewBuilder11.build();
        c.a aVarNewBuilder12 = c.newBuilder();
        aVarNewBuilder12.setResponseCode(0);
        l = aVarNewBuilder12.build();
        c.a aVarNewBuilder13 = c.newBuilder();
        aVarNewBuilder13.setResponseCode(-1);
        aVarNewBuilder13.setDebugMessage("Service connection is disconnected.");
        m = aVarNewBuilder13.build();
        c.a aVarNewBuilder14 = c.newBuilder();
        aVarNewBuilder14.setResponseCode(2);
        aVarNewBuilder14.setDebugMessage("Timeout communicating with service.");
        n = aVarNewBuilder14.build();
        c.a aVarNewBuilder15 = c.newBuilder();
        aVarNewBuilder15.setResponseCode(-2);
        aVarNewBuilder15.setDebugMessage("Client does not support subscriptions.");
        o = aVarNewBuilder15.build();
        c.a aVarNewBuilder16 = c.newBuilder();
        aVarNewBuilder16.setResponseCode(-2);
        aVarNewBuilder16.setDebugMessage("Client does not support subscriptions update.");
        p = aVarNewBuilder16.build();
        c.a aVarNewBuilder17 = c.newBuilder();
        aVarNewBuilder17.setResponseCode(-2);
        aVarNewBuilder17.setDebugMessage("Client does not support get purchase history.");
        q = aVarNewBuilder17.build();
        c.a aVarNewBuilder18 = c.newBuilder();
        aVarNewBuilder18.setResponseCode(-2);
        aVarNewBuilder18.setDebugMessage("Client does not support price change confirmation.");
        r = aVarNewBuilder18.build();
        c.a aVarNewBuilder19 = c.newBuilder();
        aVarNewBuilder19.setResponseCode(-2);
        aVarNewBuilder19.setDebugMessage("Play Store version installed does not support cross selling products.");
        s = aVarNewBuilder19.build();
        c.a aVarNewBuilder20 = c.newBuilder();
        aVarNewBuilder20.setResponseCode(-2);
        aVarNewBuilder20.setDebugMessage("Client does not support multi-item purchases.");
        t = aVarNewBuilder20.build();
        c.a aVarNewBuilder21 = c.newBuilder();
        aVarNewBuilder21.setResponseCode(-2);
        aVarNewBuilder21.setDebugMessage("Client does not support offer_id_token.");
        u = aVarNewBuilder21.build();
        c.a aVarNewBuilder22 = c.newBuilder();
        aVarNewBuilder22.setResponseCode(-2);
        aVarNewBuilder22.setDebugMessage("Client does not support ProductDetails.");
        v = aVarNewBuilder22.build();
        c.a aVarNewBuilder23 = c.newBuilder();
        aVarNewBuilder23.setResponseCode(-2);
        aVarNewBuilder23.setDebugMessage("Client does not support in-app messages.");
        w = aVarNewBuilder23.build();
        c.a aVarNewBuilder24 = c.newBuilder();
        aVarNewBuilder24.setResponseCode(-2);
        aVarNewBuilder24.setDebugMessage("Client does not support user choice billing.");
        x = aVarNewBuilder24.build();
        c.a aVarNewBuilder25 = c.newBuilder();
        aVarNewBuilder25.setResponseCode(-2);
        aVarNewBuilder25.setDebugMessage("Play Store version installed does not support external offer.");
        y = aVarNewBuilder25.build();
        c.a aVarNewBuilder26 = c.newBuilder();
        aVarNewBuilder26.setResponseCode(5);
        aVarNewBuilder26.setDebugMessage("Unknown feature");
        z = aVarNewBuilder26.build();
        c.a aVarNewBuilder27 = c.newBuilder();
        aVarNewBuilder27.setResponseCode(-2);
        aVarNewBuilder27.setDebugMessage("Play Store version installed does not support get billing config.");
        A = aVarNewBuilder27.build();
        c.a aVarNewBuilder28 = c.newBuilder();
        aVarNewBuilder28.setResponseCode(-2);
        aVarNewBuilder28.setDebugMessage("Query product details with serialized docid is not supported.");
        B = aVarNewBuilder28.build();
        c.a aVarNewBuilder29 = c.newBuilder();
        aVarNewBuilder29.setResponseCode(4);
        aVarNewBuilder29.setDebugMessage("Item is unavailable for purchase.");
        C = aVarNewBuilder29.build();
        c.a aVarNewBuilder30 = c.newBuilder();
        aVarNewBuilder30.setResponseCode(-2);
        aVarNewBuilder30.setDebugMessage("Query product details with developer specified account is not supported.");
        D = aVarNewBuilder30.build();
        c.a aVarNewBuilder31 = c.newBuilder();
        aVarNewBuilder31.setResponseCode(-2);
        aVarNewBuilder31.setDebugMessage("Play Store version installed does not support alternative billing only.");
        E = aVarNewBuilder31.build();
        c.a aVarNewBuilder32 = c.newBuilder();
        aVarNewBuilder32.setResponseCode(5);
        aVarNewBuilder32.setDebugMessage("To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.");
        F = aVarNewBuilder32.build();
    }

    public static c a(int i2, String str) {
        c.a aVarNewBuilder = c.newBuilder();
        aVarNewBuilder.setResponseCode(i2);
        aVarNewBuilder.setDebugMessage(str);
        return aVarNewBuilder.build();
    }
}
