package defpackage;

import java.util.Set;
import kotlin.jvm.internal.Intrinsics;
import kotlin.text.Regex;

/* JADX INFO: loaded from: classes3.dex */
public final class l73 {
    public static final hz2 A;
    public static final hz2 B;
    public static final hz2 C;
    public static final hz2 D;
    public static final hz2 E;
    public static final hz2 F;
    public static final hz2 G;
    public static final hz2 H;
    public static final hz2 I;
    public static final hz2 J;
    public static final hz2 K;
    public static final hz2 L;
    public static final hz2 M;
    public static final hz2 N;
    public static final Set O;
    public static final Set P;
    public static final Set Q;
    public static final Set R;
    public static final Set S;
    public static final l73 a = new l73();
    public static final hz2 b;
    public static final hz2 c;
    public static final hz2 d;
    public static final hz2 e;
    public static final hz2 f;
    public static final hz2 g;
    public static final hz2 h;
    public static final hz2 i;
    public static final hz2 j;
    public static final hz2 k;
    public static final hz2 l;
    public static final hz2 m;
    public static final hz2 n;
    public static final Regex o;
    public static final hz2 p;
    public static final hz2 q;
    public static final hz2 r;
    public static final hz2 s;
    public static final hz2 t;
    public static final hz2 u;
    public static final hz2 v;
    public static final hz2 w;
    public static final hz2 x;
    public static final hz2 y;
    public static final hz2 z;

    static {
        hz2 hz2VarIdentifier = hz2.identifier("getValue");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier, "identifier(\"getValue\")");
        b = hz2VarIdentifier;
        hz2 hz2VarIdentifier2 = hz2.identifier("setValue");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier2, "identifier(\"setValue\")");
        c = hz2VarIdentifier2;
        hz2 hz2VarIdentifier3 = hz2.identifier("provideDelegate");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier3, "identifier(\"provideDelegate\")");
        d = hz2VarIdentifier3;
        hz2 hz2VarIdentifier4 = hz2.identifier("equals");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier4, "identifier(\"equals\")");
        e = hz2VarIdentifier4;
        hz2 hz2VarIdentifier5 = hz2.identifier("compareTo");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier5, "identifier(\"compareTo\")");
        f = hz2VarIdentifier5;
        hz2 hz2VarIdentifier6 = hz2.identifier("contains");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier6, "identifier(\"contains\")");
        g = hz2VarIdentifier6;
        hz2 hz2VarIdentifier7 = hz2.identifier("invoke");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier7, "identifier(\"invoke\")");
        h = hz2VarIdentifier7;
        hz2 hz2VarIdentifier8 = hz2.identifier("iterator");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier8, "identifier(\"iterator\")");
        i = hz2VarIdentifier8;
        hz2 hz2VarIdentifier9 = hz2.identifier("get");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier9, "identifier(\"get\")");
        j = hz2VarIdentifier9;
        hz2 hz2VarIdentifier10 = hz2.identifier("set");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier10, "identifier(\"set\")");
        k = hz2VarIdentifier10;
        hz2 hz2VarIdentifier11 = hz2.identifier("next");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier11, "identifier(\"next\")");
        l = hz2VarIdentifier11;
        hz2 hz2VarIdentifier12 = hz2.identifier("hasNext");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier12, "identifier(\"hasNext\")");
        m = hz2VarIdentifier12;
        hz2 hz2VarIdentifier13 = hz2.identifier("toString");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier13, "identifier(\"toString\")");
        n = hz2VarIdentifier13;
        o = new Regex("component\\d+");
        hz2 hz2VarIdentifier14 = hz2.identifier("and");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier14, "identifier(\"and\")");
        p = hz2VarIdentifier14;
        hz2 hz2VarIdentifier15 = hz2.identifier("or");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier15, "identifier(\"or\")");
        q = hz2VarIdentifier15;
        hz2 hz2VarIdentifier16 = hz2.identifier("xor");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier16, "identifier(\"xor\")");
        r = hz2VarIdentifier16;
        hz2 hz2VarIdentifier17 = hz2.identifier("inv");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier17, "identifier(\"inv\")");
        s = hz2VarIdentifier17;
        hz2 hz2VarIdentifier18 = hz2.identifier("shl");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier18, "identifier(\"shl\")");
        t = hz2VarIdentifier18;
        hz2 hz2VarIdentifier19 = hz2.identifier("shr");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier19, "identifier(\"shr\")");
        u = hz2VarIdentifier19;
        hz2 hz2VarIdentifier20 = hz2.identifier("ushr");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier20, "identifier(\"ushr\")");
        v = hz2VarIdentifier20;
        hz2 hz2VarIdentifier21 = hz2.identifier("inc");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier21, "identifier(\"inc\")");
        w = hz2VarIdentifier21;
        hz2 hz2VarIdentifier22 = hz2.identifier("dec");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier22, "identifier(\"dec\")");
        x = hz2VarIdentifier22;
        hz2 hz2VarIdentifier23 = hz2.identifier("plus");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier23, "identifier(\"plus\")");
        y = hz2VarIdentifier23;
        hz2 hz2VarIdentifier24 = hz2.identifier("minus");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier24, "identifier(\"minus\")");
        z = hz2VarIdentifier24;
        hz2 hz2VarIdentifier25 = hz2.identifier("not");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier25, "identifier(\"not\")");
        A = hz2VarIdentifier25;
        hz2 hz2VarIdentifier26 = hz2.identifier("unaryMinus");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier26, "identifier(\"unaryMinus\")");
        B = hz2VarIdentifier26;
        hz2 hz2VarIdentifier27 = hz2.identifier("unaryPlus");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier27, "identifier(\"unaryPlus\")");
        C = hz2VarIdentifier27;
        hz2 hz2VarIdentifier28 = hz2.identifier("times");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier28, "identifier(\"times\")");
        D = hz2VarIdentifier28;
        hz2 hz2VarIdentifier29 = hz2.identifier("div");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier29, "identifier(\"div\")");
        E = hz2VarIdentifier29;
        hz2 hz2VarIdentifier30 = hz2.identifier("mod");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier30, "identifier(\"mod\")");
        F = hz2VarIdentifier30;
        hz2 hz2VarIdentifier31 = hz2.identifier("rem");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier31, "identifier(\"rem\")");
        G = hz2VarIdentifier31;
        hz2 hz2VarIdentifier32 = hz2.identifier("rangeTo");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier32, "identifier(\"rangeTo\")");
        H = hz2VarIdentifier32;
        hz2 hz2VarIdentifier33 = hz2.identifier("timesAssign");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier33, "identifier(\"timesAssign\")");
        I = hz2VarIdentifier33;
        hz2 hz2VarIdentifier34 = hz2.identifier("divAssign");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier34, "identifier(\"divAssign\")");
        J = hz2VarIdentifier34;
        hz2 hz2VarIdentifier35 = hz2.identifier("modAssign");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier35, "identifier(\"modAssign\")");
        K = hz2VarIdentifier35;
        hz2 hz2VarIdentifier36 = hz2.identifier("remAssign");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier36, "identifier(\"remAssign\")");
        L = hz2VarIdentifier36;
        hz2 hz2VarIdentifier37 = hz2.identifier("plusAssign");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier37, "identifier(\"plusAssign\")");
        M = hz2VarIdentifier37;
        hz2 hz2VarIdentifier38 = hz2.identifier("minusAssign");
        Intrinsics.checkNotNullExpressionValue(hz2VarIdentifier38, "identifier(\"minusAssign\")");
        N = hz2VarIdentifier38;
        O = hc4.setOf((Object[]) new hz2[]{hz2VarIdentifier21, hz2VarIdentifier22, hz2VarIdentifier27, hz2VarIdentifier26, hz2VarIdentifier25});
        P = hc4.setOf((Object[]) new hz2[]{hz2VarIdentifier27, hz2VarIdentifier26, hz2VarIdentifier25});
        Q = hc4.setOf((Object[]) new hz2[]{hz2VarIdentifier28, hz2VarIdentifier23, hz2VarIdentifier24, hz2VarIdentifier29, hz2VarIdentifier30, hz2VarIdentifier31, hz2VarIdentifier32});
        R = hc4.setOf((Object[]) new hz2[]{hz2VarIdentifier33, hz2VarIdentifier34, hz2VarIdentifier35, hz2VarIdentifier36, hz2VarIdentifier37, hz2VarIdentifier38});
        S = hc4.setOf((Object[]) new hz2[]{hz2VarIdentifier, hz2VarIdentifier2, hz2VarIdentifier3});
    }

    private l73() {
    }
}
